services:
  - type: web
    name: tes-laravel
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_PORT
        value: "3306"
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql
          property: host
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

  - type: pserv
    name: mysql
    env: docker
    dockerfilePath: ./mysql/Dockerfile
    plan: starter
    autoDeploy: false
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: tes_laravel
      - key: MYSQL_USER
        value: laravel
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
